<?php echo $this->doctype() . PHP_EOL; ?>
<html lang="en">
<head>
<meta charset="utf-8" />
<base href="<?php echo $this->baseUrl(); ?>" />
<?php
    // add default styles
    $this->headLink()
        ->appendStylesheet($this->baseUrl() . '/css/blueprint/screen.css', 'screen, projection')
        ->appendStylesheet($this->baseUrl() . '/css/blueprint/print.css', 'print')
        ->appendStylesheet($this->baseUrl() . '/css/blueprint/ie.css', 'screen, projection', 'lt IE 8')
        ->appendStylesheet($this->baseUrl() . '/css/html5.css', 'screen, projection', 'lt IE 9')
        ->appendStylesheet($this->baseUrl() . '/css/style.css')
        ->appendStylesheet($this->baseUrl() . '/css/general.css')
        ->appendStylesheet($this->baseUrl() . '/css/style.css')
        ->appendStylesheet($this->baseUrl() . '/css/ie6.css', 'screen, projection', 'IE 6')
        ->appendStylesheet($this->baseUrl() . '/css/ie.css', '', 'IE')
        ;

    $this->headScript()
        ->prependFile('http://html5shim.googlecode.com/svn/trunk/html5.js', 'text/javascript', array(
            'conditional' => 'lt IE 9'
        ))
        ->prependFile($this->baseUrl() . '/js/jquery-1.9.1.min.js')
        ;
?>
<?php echo $this->headTitle(); ?>
<?php echo $this->headMeta() . PHP_EOL; ?>
<?php echo $this->headLink() . PHP_EOL; ?>
<?php echo $this->headScript() . PHP_EOL; ?>

</head>
<body>
<div id="container">
  <header>
    <nav>
      <ul role="menu">
        <li role="menuitem"><a href="/">Home</a></li>
        <li role="menuitem"><a href="/index/subform">Example</a></li>
        <li role="menuitem"><a href="/index/source-code">Source code</a></li>
        <li role="menuitem"><a href="/index/credits">Credits</a></li>
      </ul>
      <div class="cb"></div>
    </nav>
  </header>
  <section>
    <article id="content">
<?php echo $this->layout()->content; ?>
    </article>
  </section>
  <footer>
<?php $year = (int) date('Y'); ?>
    <p>Copyright &copy; 2013<?php if ($year !== 2013) { echo '-' . $year; } ?> Tomasz Kuter. All rights reserved!</p>
  </footer>
</div>
<script type="text/javascript">
$(document).ready(function() {
	// Handler for .ready() called.
});
</script>
</body>
</html>